deployment:
  tasks:
    - pwd

    - ls -la

    - git log --oneline -n 1

    - export DEPLOYPATH=/home/simpelar/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - echo "Deployment completed successfully!"
